export { default as Navbar } from "./Navbar/Navbar"
export { default as Hero } from "./Hero/Hero"
export { default as Sidebar } from "./Sidebar/Sidebar"
export { default as Products } from "./Products/Products"
export { default as Featured } from "./Featured/Featured"
export { default as Footer } from "./Footer/Footer"
export { default as Practice } from "../Components/Practice/Practice"
